Создана главная страница и меню
ProjectMeowInc/meowlib.frontend.remaster pull request #24
Opened 2023-12-13 19:15 UTC by k3ssL

2023-12-20 11:23 UTC, BlackSoulHub requested changes
Так же @Lx1Cx добавь в этот PR базовый роутинг

2023-12-21 06:35 UTC, BlackSoulHub requested changes

2023-12-24 05:49 UTC, BlackSoulHub requested changes
Детальное ревью проведёт @Lx1Cx. Не забудь просмотреть итоговую вёрстку

2023-12-24 07:19 UTC, Lx1Cx requested changes

2023-12-26 06:44 UTC, Lx1Cx requested changes

2023-12-27 16:02 UTC, BlackSoulHub requested changes

2023-12-27 17:18 UTC, merged