Сделано управление пользователями
ProjectMeowInc/meowlib.frontend.remaster pull request #34
Opened 2023-12-27 17:39 UTC by k3ssL

2023-12-28 18:55 UTC, BlackSoulHub requested changes

2023-12-28 18:55 UTC, BlackSoulHub commented on src/entities/Users/service/UsersService.ts
> +
Лишний отступ

2023-12-28 18:55 UTC, BlackSoulHub commented on src/entities/Users/models/response/IGetAllUsersResponse.ts
> +    } []
Лишний отступ

2023-12-28 18:55 UTC, BlackSoulHub commented on src/entities/Users/models/requests/IUpdateUserByIdRequest.ts
> +    role: User
`UserRole`

2023-12-28 18:55 UTC, BlackSoulHub commented on src/entities/Users/models/dto/IUserDTO.ts
> +    role: User
`UserRole`

2023-12-31 09:14 UTC, BlackSoulHub requested changes

2023-12-31 09:14 UTC, BlackSoulHub commented on src/entities/Users/service/UsersService.ts
> +
Отступ

2023-12-31 09:14 UTC, BlackSoulHub commented on src/entities/Users/service/UsersService.ts
> +    static async getUserById(usersId: number) {
Укажи возвращаемый тип. А то будет неявно использован UserApi тип

2023-12-31 09:14 UTC, BlackSoulHub commented on src/pages/admin/users/MainUsersPage/MainUsersPage.tsx
> +    const [userList, setUserList] = useState<IUserDTO[] | null>(null)
`users`

2023-12-31 09:14 UTC, BlackSoulHub commented on src/pages/admin/users/MainUsersPage/MainUsersPage.tsx
> +    useEffect(() => {
Нужен `useFirstLoading`. Менять не нужно

2023-12-31 09:14 UTC, BlackSoulHub commented on src/entities/Users/api/UsersApi.ts
> +
Отступы

2023-12-31 09:14 UTC, BlackSoulHub commented on src/pages/admin/users/UpdateUserPage/UpdateUserForm/UpdateUserForm.tsx
> +const UpdateUserForm: FC<IUpdateUserProps> = ({ user }) => {
Не должно ли это лежать в `UI`?

2023-12-31 09:14 UTC, BlackSoulHub commented on src/pages/admin/users/UpdateUserPage/useUpdateUserForm.ts
> +export const useUpdateUserForm = (id: number) => {
Название хука должно соответствовать названию компонента  в котором он используется.
И он должен лежать рядом с компонентом в котором используется.

Для `useUpdateUserForm` компонент: `UpdateUserForm`

2023-12-31 09:14 UTC, BlackSoulHub commented on src/pages/admin/users/UpdateUserPage/UpdateUserPage.tsx
> +import classes from "@/pages/admin/tags/UpdateTagPage/updateTagPage.module.css";
В `UpdateUserPage` используются классы из `UpdateTagPage`

2023-12-31 09:14 UTC, BlackSoulHub commented on src/pages/admin/users/UpdateUserPage/UpdateUserPage.tsx
> +import {IUpdateUserByIdRequest} from "@/entities/Users/models/requests/IUpdateUserByIdRequest";
Думаю стоит почистить `import`

2023-12-31 10:06 UTC, BlackSoulHub approved these changes, later dismissed

2023-12-31 10:23 UTC, BlackSoulHub requested changes

2023-12-31 10:23 UTC, BlackSoulHub commented on src/pages/admin/users/UI/UpdateUserForm/UpdateUserForm.tsx
> +            <Input name={'role'} placeholder={'Введите роль'} onChange={ChangeHandler} style={{margin: 10}}/>
Замени на что-нибудь, что сделаем список ролей. А не написание произвольной строки

2023-12-31 14:48 UTC, Lx1Cx requested changes

2023-12-31 14:48 UTC, Lx1Cx commented on src/pages/admin/users/UI/UserItem/UserItem.tsx
> +    href: string
Как-будто href не используется

2023-12-31 14:50 UTC, Lx1Cx approved these changes, later dismissed

2023-12-31 15:15 UTC, BlackSoulHub requested changes

2023-12-31 15:15 UTC, BlackSoulHub commented on src/pages/admin/users/UI/UpdateUserForm/useUpdateUserForm.ts
> +        role: UserRoleEnum.User || UserRoleEnum.Admin || UserRoleEnum.Moderator || UserRoleEnum.Editor,
Как это понимать?

2023-12-31 15:16 UTC, BlackSoulHub approved these changes

2023-12-31 15:20 UTC, merged