Создана возможность добавление книги в избранное
ProjectMeowInc/meowlib.frontend.remaster pull request #58
Opened 2024-01-10 17:45 UTC by k3ssL

2024-01-11 02:38 UTC, BlackSoulHub requested changes
Кстати. Заметил, что ты не соблюдаешь наши "конвенции". 
Хотя возможно их никто не объяснял.
Попробуй:
```bash
npm run custom-lint
```

или
```bash
npm run custom-lint-auto-fix
```
Но учитывай, что `custom-lint-auto-fix` не доделан и к использованию не рекомендуется. Он исправляет нейминг файлов, но сбивает импорты

2024-01-11 02:38 UTC, BlackSoulHub commented on src/entities/UserFavorite/service/UserFavoriteService.ts
> +    static async addBookInFavorite(requestData: IAddBookInFavoriteRequest): Promise<EmptyResult> {
request в сервисах. Можешь просто разложить его на отдельные параметры

2024-01-11 02:38 UTC, BlackSoulHub commented on src/pages/MainPage/UI/BookPreview/BookPreview.tsx
> +    const { handleHover, hover } = useBookPreview(id, "InPlans")
Судя по всему ты его не залил

2024-01-11 02:38 UTC, BlackSoulHub commented on src/pages/MainPage/UI/BookPreview/BookPreview.tsx
> +    const { handleHover, hover } = useBookPreview(id, "InPlans")
Несколько вопросов:
1. Зачем ты изменяешь `BookPreview`? Ты хочешь сделать для пользователя статус добавленной книги на главной странице? Хотя это звучит неплохо, но это - не то, что пока нужно. Тебе нужно изменить страницу книги. Роут вроде: `books/{bookId}`.
2. Помимо этого могу предположить, что `InPlans` в данном случае - стандартное значение для книги. Но отображать нужно не так. Тебе нужно отображать то, в каком статусе находится книга у конкретного пользователя. 
Стоит учитывать: 
- Пользователь может быть не авторизован (гость). Тогда статуса книги всегда нет. Пуская будет что-то вроде кнопки: `Добавить в избранное` при нажатии на которую пользователя попросят авторизоваться.
- Пользователь может НЕ иметь книгу данную книгу в избранном. Тогда можешь сделать тоже, что и с гостем, но при нажатии должен быть список возможных вариантов
- Пользователь может уже добавить данную книгу в свой список. Тогда должна быть возможность перенести книгу в ДРУГОЙ список

2024-01-17 10:36 UTC, BlackSoulHub requested changes

2024-01-17 10:36 UTC, BlackSoulHub commented on src/entities/UserFavorite/api/UserFavoriteApi.ts
> +            .withUrl(`/v1/ysers/favorite/my/book/${bookId}`)
url

2024-01-17 10:36 UTC, BlackSoulHub commented on src/entities/UserFavorite/models/dto/IAddUserFavoriteDTO.ts
> +export interface IAddUserFavoriteDTO {
Нет смысла в этом интерфейсе. Используй сигнатуру функции:

```ts
async function addUserFavoriteAsync(bookId: number, status: UserBookStatus): Promise<EmptyResult> {
    // logic...
}

```

2024-01-17 10:36 UTC, BlackSoulHub commented on src/entities/UserFavorite/models/dto/IShortUserFavoriteDTO.ts
> +export interface IShortUserFavoriteDTO {
Название модели в единственном числе. При это представляет собой модель - список книг, добавленных пользователем.

2024-01-17 10:36 UTC, BlackSoulHub commented on src/entities/UserFavorite/models/dto/IUserFavoriteDTO.ts
> +export interface IUserFavoriteDTO {
Модель короче чем, `IShortUserFavoriteDTO`. Всё те же вопросы

2024-01-17 10:36 UTC, BlackSoulHub commented on src/pages/BookPages/BookPage/UI/BookImage/BookImage.tsx
> +    const [selectedStatus, setSelectedStatus] = useState<UserBookStatus | null>(null)
логика в компоненте

2024-01-17 10:36 UTC, BlackSoulHub commented on src/pages/BookPages/BookPage/UI/BookImage/BookImage.tsx
> +                <SelectStatusButton
Ты сделал кнопку для добавления книги в список пользователя. Удали старую кнопку: `Добавить в список`

2024-01-17 10:36 UTC, BlackSoulHub commented on src/pages/BookPages/BookPage/UI/SelectStatusButton/useSelectStatusButton.ts
> +    function isLogIn(): boolean {
Вынеси временно в `TokenService`

2024-01-17 10:36 UTC, BlackSoulHub commented on src/pages/BookPages/BookPage/UI/SelectStatusButton/useSelectStatusButton.ts
> +    async function ClickStatusHandler(status: UserBookStatus) {
Пробел

2024-01-17 10:36 UTC, BlackSoulHub commented on src/pages/BookPages/BookPage/UI/SelectStatusButton/useSelectStatusButton.ts
> +            window.location.href = "/auth"
Замени на `RedirectService`

2024-01-17 10:36 UTC, BlackSoulHub commented on src/pages/BookPages/BookPage/UI/SelectStatusButton/useSelectStatusButton.ts
> +        return AlertService.successMessage("Книга была добавлена")
После успешного добавления текущий статус книги не обновляется?

2024-01-17 10:36 UTC, BlackSoulHub commented on src/pages/BookPages/BookPage/UI/SelectStatusButton/SelectStatusButton.tsx
> +                    ? <p>Текущий статус: {selectedStatus}</p>
Это не должно быть в виде отдельного блока. Сделай подпись на кнопке. В случае, если книга не добавлена в список пользователя напиши: "Добавить в список"

2024-01-18 19:36 UTC, k3ssL commented on src/shared/UI/button/Button.tsx
> +    children: any
насчет этого момента.
Я не знаю какой тип данных здесь поставить, потому что компонент уже используется и изменения приведут к поломке

2024-01-19 02:30 UTC, BlackSoulHub commented on src/shared/UI/button/Button.tsx
> +    children: any
```suggestion
    children: string
```

```tsx
<Button onClick={ClickHandler} styles={{margin: "15px"}}>
    {selectedStatus
        ? getPrettyBookStatusName(selectedStatus)
        : "Добавить в список"
    }
</Button>
```

2024-01-19 02:48 UTC, BlackSoulHub requested changes

2024-01-19 02:48 UTC, BlackSoulHub commented on src/pages/BookPages/BookPage/UI/SelectStatusButton/SelectStatusButton.tsx
> +                    ? <p>{getPrettyBookStatusName(selectedStatus)}</p>
Кнопка должна быть такого-же размера как и верхняя кнопка. Так выглядит странно
![image](https://github.com/ProjectMeowInc/meowlib.frontend.remaster/assets/86704101/06447aa4-13bc-436a-9a81-e9e5133fc4fa)

2024-01-19 12:52 UTC, BlackSoulHub approved these changes

2024-01-19 12:52 UTC, merged