Сделано управление командами
ProjectMeowInc/meowlib.frontend.remaster pull request #61
Opened 2024-01-17 01:46 UTC by Lx1Cx

2024-01-18 04:33 UTC, BlackSoulHub commented on src/entities/Team/services/TeamService.ts
> +    static async removePeopleFromTeamAsync(teamId: number, userId: number) {
Укажи тип возвращаемого значения

2024-01-21 12:04 UTC, BlackSoulHub commented on src/pages/TeamPages/TeamsPage/UI/Controls/Controls.tsx
> +    page: string
number

2024-01-25 22:08 UTC, Lx1Cx commented
Сделана страница команды, осталось только доделать управление командами ()
![image](https://github.com/ProjectMeowInc/meowlib.frontend.remaster/assets/89466562/a45df65c-48c9-43bb-9e5a-1909fbf66352)

2024-02-03 11:28 UTC, BlackSoulHub requested changes

2024-02-03 11:28 UTC, BlackSoulHub commented on src/app/(withMenu)/teams/[teamId]/page.tsx
> +            description: "The best library of ranobe in the world",
На русском

2024-02-03 11:28 UTC, BlackSoulHub commented on src/entities/Notification/types/NotificationTeamInvitePayload.ts
> +export type NotificationTeamInvitePayload = {
Почему это `type` а не интерфейс?

2024-02-03 11:28 UTC, BlackSoulHub commented on src/pages/TeamPages/TeamPage/UI/Members/Members.tsx
> +    const {userIsAdmin, modalIsActive, setModalIsActive, isUserInTeam} = useMembers(members)
`userIsTeamAdmin`

2024-02-03 11:28 UTC, BlackSoulHub commented on src/pages/TeamPages/TeamPage/UI/Members/Members.tsx
> +const Members: FC<IMembersProps> = ({members}) => {
`MembersList`?

2024-02-03 11:28 UTC, BlackSoulHub commented on src/pages/TeamPages/TeamPage/UI/Books/Books.tsx
> +const Books = () => {
`BooksList`?

2024-02-03 11:28 UTC, BlackSoulHub commented on src/pages/TeamPages/TeamPage/UI/Members/UI/AddMember/AddMember.tsx
> +const AddMember: FC<IAddMemberProps> = ({onClick}) => {
`AddMemberButton`?

2024-02-03 11:28 UTC, BlackSoulHub commented on src/pages/TeamPages/TeamPage/UI/Members/UI/LeaveFromTeam/LeaveFromTeam.tsx
> +const LeaveFromTeam = () => {
`LeaveFromTeamButton`?

2024-02-03 11:28 UTC, BlackSoulHub commented on src/pages/TeamPages/TeamPage/UI/Members/UI/LeaveFromTeam/useLeaveFromTeam.ts
> +export const useLeaveFromTeam = () => {
Переименуй в соответствии с компонентом

2024-02-03 11:28 UTC, BlackSoulHub commented on src/pages/TeamPages/TeamPage/UI/Members/UI/LeaveFromTeam/useLeaveFromTeam.ts
> +            return
Это не должно произойти. Сделай выбрасывание исключения

2024-02-03 11:28 UTC, BlackSoulHub commented on src/pages/TeamPages/TeamPage/UI/Members/UI/LeaveFromTeam/useLeaveFromTeam.ts
> +        window.location.reload()
Сделай хук/сервис

2024-02-03 11:28 UTC, BlackSoulHub commented on src/pages/TeamPages/TeamPage/UI/Members/UI/Member/useMember.ts
> +        window.location.reload()
Хук/сервис

2024-02-03 11:28 UTC, BlackSoulHub commented on src/pages/TeamPages/TeamPage/UI/Members/UI/Member/useMember.ts
> +    const params = useParams<{teamId: string}>()
Можно принимать их из места вызова `useMember`

2024-02-03 11:28 UTC, BlackSoulHub commented on src/pages/TeamPages/TeamPage/UI/Members/UI/SelectRoleModel/useSelectRoleModal.ts
> +        closeModalFunc.call(null)
`onCloseModal`?

2024-02-03 11:28 UTC, BlackSoulHub commented on src/pages/TeamPages/TeamPage/UI/Members/useMembers.ts
> +            if (u.id === user.id && u.role === "Admin") {
Почему ты пытаешься сравнивать роль в JWT токене?
Роль в токене - роль на сайте
Роль в команде - совсем другое

2024-02-03 11:28 UTC, BlackSoulHub commented on src/pages/TeamPages/TeamPage/UI/TeamInfo/TeamInfo.tsx
> +const TeamInfo: FC<ITeamInfoProps> = ({name, description}) => {
`TeamInfoBlock`?

2024-02-03 11:28 UTC, BlackSoulHub commented on src/pages/TeamPages/TeamPage/UI/TeamInfo/UI/Stats/Stats.tsx
> +const Stats: FC<IStatsProps> = ({likes, chapters, titles}) => {
`TeamStatsProps`?

2024-02-03 11:28 UTC, BlackSoulHub commented on src/pages/TeamPages/TeamPage/UI/UserModal/UserModal.tsx
> +const UserModal: FC<IUserModalProps> = ({onClick}) => {
`TeamUsersModal`?

2024-02-03 11:28 UTC, BlackSoulHub commented on src/pages/TeamPages/TeamsPage/TeamsPage.tsx
> +        page: string
number

2024-02-03 11:28 UTC, BlackSoulHub commented on src/pages/TeamPages/TeamsPage/UI/Controls/Controls.tsx
> +const Controls: FC<IControlsProps> = ({page}) => {
`TeamPageControls`

2024-02-03 11:28 UTC, BlackSoulHub commented on src/pages/TeamPages/TeamsPage/UI/CreateTeam/UI/CreateForm/useCreateTeamForm.ts
> +        window.location.reload()
Хук/сервис

2024-02-03 11:28 UTC, BlackSoulHub commented on src/pages/TeamPages/TeamsPage/UI/CreateTeam/useCreateTeam.ts
> +            setUserIsLogin(true)
Не думаю, что логика корректна. `getAccessToken` вроде не проверяет время истечения токена

2024-02-03 13:46 UTC, BlackSoulHub submitted a review, later dismissed

2024-02-03 13:47 UTC, merged